### ISSUE TITLE
automatic authentication

### ISSUE THREAD

**Issue by o-ayoub** [jcubic/jquery.terminal-www#16]
Hello,
Is it possible to make authentication automatically without prompt user to enter a username & password. 
When the page is loaded, auto login using a username and password; of course if there is invalid credentials, show a message error.
Thanks

**Comment by jcubic** [comment]
Yes but only if you use `user` and `token`. You can't auto login with password.

**Comment by jcubic** [comment]
This is was only create for case when you have two tabs open and you login to one and want to be logged in into second one. Maybe there will be possible to make it to accept the password as well, not sure how the API should look like because it now have 2 parameters `user` and `token` maybe 3rd parameter. Here are [docs for the function/method](https://terminal.jcubic.pl/api_reference.php#autologin).

**Comment by jcubic** [comment]
Sorry didn't notice that you ask in jQuery Terminal website page. For what you want to login?

**Comment by jcubic** [comment]
no reply. closing
